<?php

// Fiches K-Dramas (version française).
// 'resume' est une liste de paragraphes ; 'casting' associe chaque acteur à sa photo.
// Les champs vides ou absents ne sont pas affichés.

$categorie3 = [
    [
        'id' => 1,
        'titre' => 'Indulgence',
        'sous_titre' => 'Desire to Flirt',
        'poster' => 'images/image1.png',
        'resume' => [
            'Suite à un tragique accident de voiture, deux amis d’enfance sont séparés. Plusieurs années plus tard, ils se retrouvent en tant que frère et sœur adoptifs. Ils s’interrogent et se testent mutuellement, naviguant dans le labyrinthe de l’amour et des querelles familiales potentielles.',
            'Après de nombreuses épreuves, ils travaillent ensemble pour découvrir la vérité derrière cet accident fatidique.',
        ],
        'episodes_total' => '13',
        'durer' => '10 min',
        'diffuser_le' => 'Du lundi au dimanche',
        'reseau_origine' => 'Youku',
        'pays' => 'Chine',
        'statue' => 'Terminé',
        'sortie' => '2024',
        'genre' => 'Roman ; Romance ; Série web',
        'casting' => [
            ['nom' => 'Hebe Feng', 'image' => 'images/image2.png'],
            ['nom' => 'Guansen Zhang', 'image' => 'images/image3.png'],
            ['nom' => 'Wang Jun Hao', 'image' => 'images/image4.png'],
            ['nom' => 'Li Ting Zhe', 'image' => 'images/drama15.jpg'],
        ],
        'video_titre' => 'Bande-annonce d’Indulgence (2024)',
        'youtube_link' => 'https://www.youtube.com/watch?v=L_b4i_7WeS0',
        'video' => 'https://www.youtube-nocookie.com/embed/L_b4i_7WeS0',
    ],
    [
        'id' => 2,
        'titre' => 'Chasseurs de badlands',
        'sous_titre' => 'Badland Hunters, spin-off de Concrete Utopia',
        'poster' => 'images/image5.png',
        'resume' => [
            'Un tremblement de terre a transformé Séoul en désert apocalyptique. Les survivants doivent affronter non seulement les menaces de la nature, mais aussi les autres survivants, car ce monde sans loi n’est gouverné que par la force.',
            'Parmi eux, Nam San est un chasseur de friches. Il travaille avec Choi Ji Wan.',
        ],
        'episodes_total' => '1 (film)',
        'durer' => '1 h 47',
        'diffuser_le' => 'Sortie le 26 janvier 2024',
        'reseau_origine' => 'Netflix',
        'pays' => 'Corée du Sud',
        'statue' => 'Terminé',
        'sortie' => '2024',
        'genre' => 'Action ; Drame',
        'casting' => [
            ['nom' => 'Ma Dong-seok', 'image' => 'images/image5.1.png'],
            ['nom' => 'Roh Jeong-eui', 'image' => 'images/image5.2.png'],
            ['nom' => 'Jun', 'image' => 'images/image5.4.png'],
            ['nom' => 'Lee Han-joo', 'image' => 'images/image5.3.png'],
            ['nom' => 'Lee Hee-joon', 'image' => 'images/image5.5.png'],
        ],
        'video_titre' => 'Bande-annonce de Badland Hunters (2024)',
        'youtube_link' => 'https://www.youtube.com/watch?v=HlUkRYLdlQg',
        'video' => 'https://www.youtube-nocookie.com/embed/HlUkRYLdlQg',
    ],
    [
        'id' => 3,
        'titre' => 'Kingmaker : Le changement du destin',
        'sous_titre' => 'Vent, nuage et pluie',
        'poster' => 'images/image6.png',
        'resume' => [
            'À la fin de la période Joseon, la série suit le physionomiste Choi Chun Joong alors qu’il tente de construire une nation idéale. Considéré comme le plus grand devin et physionomiste de Joseon, il est un héros des temps troublés et nourrit la grande ambition de bâtir un nouveau pays après avoir renversé Joseon, ruiné par les hommes au pouvoir.',
            'D’une belle apparence, Choi Chun Joong est un homme raffiné qui excelle dans les arts, notamment les arts martiaux, les jeux de hasard, le chant et la danse. C’est aussi un romantique qui met tout en œuvre pour la femme qu’il aime. Avec le sens des mots et un esprit brillant pour la politique, il fera de Yi Ha Eung l’homme le plus puissant de Joseon, de son fils Lee Jae Hwang un roi et de Min Ja Young, une fille des rues, l’impératrice de Joseon.',
            'Adaptée du roman « Baramgwa Gooreumgwa Bi » de Lee Byung Joo (publié de 1977 à 1987 dans le journal The Chosun Ilbo), l’histoire mêle personnages fictifs et véritables personnages historiques.',
        ],
        'episodes_total' => '21',
        'durer' => '1 h',
        'diffuser_le' => 'À partir du 17 mai 2020',
        'reseau_origine' => 'TV Chosun',
        'pays' => 'Corée du Sud',
        'statue' => 'Terminé',
        'sortie' => '2020',
        'genre' => 'Drame ; Fantaisie ; Historique ; Romance ; Surnaturel',
        'casting' => [
            ['nom' => 'Jo Bok-rae', 'image' => 'images/image6.1.png'],
            ['nom' => 'Noh Hyeong-wook', 'image' => 'images/image6.2.png'],
            ['nom' => 'Park Jeong-yeon', 'image' => 'images/image6.3.png'],
            ['nom' => 'Kang Tae-woo', 'image' => 'images/image6.4.png'],
        ],
        'video_titre' => 'Bande-annonce de Kingmaker : Le changement du destin',
        'youtube_link' => 'https://www.youtube.com/watch?v=1uXLgYvG-OY',
        'video' => 'https://www.youtube-nocookie.com/embed/1uXLgYvG-OY',
    ],
    [
        'id' => 4,
        'titre' => 'Stealth Walker',
        'sous_titre' => 'Mei Gui Xing Zhe',
        'poster' => 'images/image3.0.png',
        'resume' => [
            'L’histoire d’un groupe de jeunes policiers qui démantèlent des organisations de trafic de drogue.',
        ],
        'episodes_total' => '10',
        'durer' => '50 min',
        'diffuser_le' => 'Du 11 au 27 août 2021',
        'reseau_origine' => 'Youku',
        'pays' => 'Chine',
        'statue' => 'Terminé',
        'sortie' => '2021',
        'genre' => 'Policier ; Amitié ; Enquête ; Romance ; Suspense ; Série web',
        'casting' => [
            ['nom' => 'Peng Ling', 'image' => 'images/image3.1.png'],
            ['nom' => 'Zheng Ye Cheng', 'image' => 'images/image3.2.png'],
            ['nom' => 'Kim Ji-woong', 'image' => 'images/image33.png'],
            ['nom' => 'Li Zi Feng', 'image' => 'images/image3.4.png'],
        ],
        'video_titre' => 'Bande-annonce de Stealth Walker (2021)',
        'youtube_link' => 'https://www.youtube.com/watch?v=GQhU9SVkQdk',
        'video' => 'https://www.youtube-nocookie.com/embed/GQhU9SVkQdk',
    ],
    [
        'id' => 5,
        'titre' => 'The Sweet Blood',
        'sous_titre' => 'Daldarhan Keu Nom',
        'poster' => 'images/image2.10.png',
        'resume' => [
            'Né d’une mère humaine et d’un père vampire, Yeon Seo est une demi-vampire de 118 ans qui ne veut rien d’autre que vivre une vie humaine ordinaire. Elle a choisi de se fondre parmi les jeunes de son âge apparent et doit désormais relever l’un des défis les plus difficiles de la vie : obtenir son diplôme de fin d’études secondaires.',
            'Luttant contre ses pulsions de vampire, Yeon Seo fait de son mieux pour passer inaperçue à l’école, jusqu’à ce que le sang si doux de son camarade de classe Song Meo Roo attire l’attention des vampires et des loups-garous. Essayant d’ignorer l’appel de ce sang, elle prend sur elle de protéger son camarade de ceux qui le chassent.',
            'Déchirée entre son devoir familial et les désirs de son cœur, Yeon Seo parviendra-t-elle à embrasser son humanité et à résister à la tentation, ou sa part vampire finira-t-elle par l’emporter ?',
        ],
        'episodes_total' => '15',
        'diffuser_le' => 'À partir du 7 avril 2021 (mercredi et samedi)',
        'reseau_origine' => 'YouTube (B-PLAY)',
        'pays' => 'Corée du Sud',
        'statue' => 'Terminé',
        'sortie' => '2021',
        'genre' => 'Fantastique ; Romance ; Vampires ; Série web',
        'casting' => [
            ['nom' => 'Kim Eo-jin', 'image' => 'images/image2.1.png'],
            ['nom' => 'Song Chae-yoon', 'image' => 'images/image2.2.png'],
            ['nom' => 'Jo Eun-ho', 'image' => 'images/image2.3-1998.png'],
            ['nom' => 'Kim Tae-hwan', 'image' => 'images/image2.4.png'],
        ],
        'video_titre' => 'Bande-annonce de The Sweet Blood (2021)',
        'youtube_link' => 'https://www.youtube.com/watch?v=qB6lC96tXUc',
        'video' => 'https://www.youtube-nocookie.com/embed/qB6lC96tXUc',
    ],
];
