<?php

// Manga entries (English version).
// 'texte' is the summary (list of paragraphs), 'description' a short presentation.

return [
    [
        'id' => 1,
        'titre' => 'Chainsaw Man Vol. 1',
        'sous_titre' => 'Denji and the Chainsaw Devil',
        'image' => 'images/mangas10.jpg',
        'texte' => [
            'Young Denji has a simple dream: to live a happy and peaceful life, spending time with the girl he loves. Reality is very different: the yakuza force him to hunt devils to pay off his crushing debts. Using his devil companion Pochita as a weapon, he will do anything for a little money.',
            'Alas, he is no longer useful and is murdered by a devil under contract with the yakuza. In an unexpected turn of events, Pochita merges with Denji’s dead body and grants him the powers of a chainsaw devil. Able to turn parts of his body into chainsaws, the resurrected Denji uses his new abilities to eliminate his enemies quickly and brutally.',
            'The official devil hunters who arrive at the scene admire him and offer him a job at the Public Safety Bureau. Now able to face the toughest enemies, Denji will stop at nothing to achieve his teenage dreams.',
        ],
        'description' => 'The first volume of an action-horror series published in Weekly Shonen Jump, mixing brutal fights and dark humour.',
        'genre' => 'Shonen - Action - Horror - Fantasy',
        'date' => '2020',
        'nombre_de_tomes' => '11',
        'nombre_de_pages' => '192',
        'note' => '4.5/5',
        'prix' => '7.99 €',
        'auteurs' => ['Tatsuki Fujimoto'],
    ],
    [
        'id' => 2,
        'titre' => 'Stranger Case Vol. 1',
        'sous_titre' => 'In/Spectre',
        'image' => 'images/mangastome1.webp',
        'texte' => [
            'As a child, Kotoko was abducted and maimed to become the “goddess of wisdom” of the yokai and other supernatural creatures. Since then, she has served as a link between their world and the human one.',
            'Things get complicated when she falls for Kuro, a heartbroken young man who seems to have a strange effect on these fabulous beings: they are terrified at the very sight of him! What is his secret? Will he be able to help Kotoko in her obscure mission?',
        ],
        'description' => 'A manga halfway between mystery and fantasy, where Kotoko’s logic is used to solve cases involving humans and supernatural creatures.',
        'genre' => 'Action - Comedy - Drama - Supernatural',
        'date' => '16/10/2015',
        'nombre_de_tomes' => '20',
        'nombre_de_pages' => '191',
        'note' => '8.64/10',
        'prix' => '7.20 €',
        'auteurs' => ['Kyo Shirodaira', 'Chashiba Katase'],
    ],
    [
        'id' => 3,
        'titre' => 'Solo Leveling Vol. 1',
        'sous_titre' => 'The World’s Weakest Hunter',
        'image' => 'images/mangas2tome2.webp',
        'texte' => [
            'When strange portals appeared all over the world, humanity had to find a way not to be slaughtered by the monsters they let through. The solution? Hunters! These fearless fighters rush into the heart of dimensional dungeons to fight the creatures inside and collect treasure.',
            'Jin Woo is the weakest of all hunters: one day, during a raid, he dies. Just when he thought his life was over, he wakes up in a hospital with a strange power: a virtual interface lets him level up to become stronger! Is this Jin Woo’s chance to take revenge and rise to the rank of the most powerful hunter?',
        ],
        'description' => 'Originally a Korean webtoon (manhwa), Solo Leveling follows the meteoric rise of a hunter considered the weakest of them all.',
        'genre' => 'Action - Fantasy',
        'date' => '07/04/2021',
        'nombre_de_tomes' => '14',
        'nombre_de_pages' => '190',
        'note' => '9.4/10',
        'prix' => '14.95 €',
        'auteurs' => ['Chugong', 'Jang Seong-rak'],
    ],
    [
        'id' => 4,
        'titre' => 'Mashle Vol. 1',
        'sous_titre' => 'Magic and Muscles',
        'image' => 'images/mangas4tome1.webp',
        'texte' => [
            'In a world where magic is law, once upon a time there was Mash Burnedead! Raised deep in the forest, the young boy spends his days between weight training and eating cream puffs. But one day, a police officer discovers his secret: he was born without magical powers, which is forbidden by law!',
            'To survive and live in peace with his father, he will have to apply to Easton, a prestigious magic academy, and become its best student. With his steel muscles and extraordinary strength, Mash intends to smash every spell and break the rules of this society.',
        ],
        'description' => 'A hilarious and energetic first volume: in a world where magic means survival, a hero with no magic gets by on sheer punching power.',
        'genre' => 'Action - Adventure - Comedy - Fantasy',
        'date' => '04/06/2020',
        'nombre_de_tomes' => '18',
        'nombre_de_pages' => '189',
        'note' => '8.85/10',
        'prix' => '6.99 €',
        'auteurs' => ['Hajime Komoto'],
    ],
    [
        'id' => 5,
        'titre' => 'One-Punch Man Vol. 1',
        'sous_titre' => 'Saitama versus everyone',
        'image' => 'images/mangas5tome1.webp',
        'texte' => [
            'When the superhero Saitama faces his enemies, they never take him seriously. With his rather ordinary build and casual attitude, there is not much to be afraid of. Yet Saitama has colossal power that lets him crush his opponents in a single blow!',
            'This power comes from three years of extremely intense training, so intense that he lost his hair. The problem is that ever since, he has been bored: nobody has been able to match him and he desperately searches for someone who can give him a real fight.',
        ],
        'description' => 'A funny and spectacular superhero parody set in a world full of monsters, where the hero is bored because he always wins.',
        'theme' => 'Aliens - Martial arts - Fights - Cyborgs - Monsters - Parody - Superheroes - Superpowers',
        'genre' => 'Action - Comedy - Science fiction - Supernatural',
        'date' => '2012',
        'nombre_de_tomes' => '29',
        'nombre_de_pages' => '188',
        'note' => '8.90/10',
        'prix' => '6.95 €',
        'auteurs' => ['ONE', 'Yusuke Murata'],
    ],
];
