<?php

// K-Drama entries (English version).
// 'resume' is a list of paragraphs; 'casting' pairs each actor with a photo.
// Empty or missing fields are not displayed.

return [
    [
        'id' => 1,
        'titre' => 'Indulgence',
        'sous_titre' => 'Desire to Flirt',
        'poster' => 'images/image1.png',
        'resume' => [
            'After a tragic car accident, two childhood friends are separated. Years later they meet again as adoptive brother and sister. They question and test each other while navigating the maze of love and potential family feuds.',
            'After many ordeals, they work together to uncover the truth behind that fateful accident.',
        ],
        'episodes_total' => '13',
        'durer' => '10 min',
        'diffuser_le' => 'Monday to Sunday',
        'reseau_origine' => 'Youku',
        'pays' => 'China',
        'statue' => 'Completed',
        'sortie' => '2024',
        'genre' => 'Novel ; Romance ; Web series',
        'casting' => [
            ['nom' => 'Hebe Feng', 'image' => 'images/image2.png'],
            ['nom' => 'Guansen Zhang', 'image' => 'images/image3.png'],
            ['nom' => 'Wang Jun Hao', 'image' => 'images/image4.png'],
            ['nom' => 'Li Ting Zhe', 'image' => 'images/drama15.jpg'],
        ],
        'video_titre' => 'Indulgence (2024) trailer',
        'youtube_link' => 'https://www.youtube.com/watch?v=L_b4i_7WeS0',
        'video' => 'https://www.youtube-nocookie.com/embed/L_b4i_7WeS0',
    ],
    [
        'id' => 2,
        'titre' => 'Badland Hunters',
        'sous_titre' => 'Spin-off of Concrete Utopia',
        'poster' => 'images/image5.png',
        'resume' => [
            'An earthquake has turned Seoul into an apocalyptic wasteland. Survivors must face not only the threats of nature but also each other, because this lawless world is ruled by power alone.',
            'Among them, Nam San is a wasteland hunter. He works with Choi Ji Wan.',
        ],
        'episodes_total' => '1 (film)',
        'durer' => '1 h 47',
        'diffuser_le' => 'Released on January 26, 2024',
        'reseau_origine' => 'Netflix',
        'pays' => 'South Korea',
        'statue' => 'Completed',
        'sortie' => '2024',
        'genre' => 'Action ; Drama',
        'casting' => [
            ['nom' => 'Ma Dong-seok', 'image' => 'images/image5.1.png'],
            ['nom' => 'Roh Jeong-eui', 'image' => 'images/image5.2.png'],
            ['nom' => 'Jun', 'image' => 'images/image5.4.png'],
            ['nom' => 'Lee Han-joo', 'image' => 'images/image5.3.png'],
            ['nom' => 'Lee Hee-joon', 'image' => 'images/image5.5.png'],
        ],
        'video_titre' => 'Badland Hunters (2024) trailer',
        'youtube_link' => 'https://www.youtube.com/watch?v=HlUkRYLdlQg',
        'video' => 'https://www.youtube-nocookie.com/embed/HlUkRYLdlQg',
    ],
    [
        'id' => 3,
        'titre' => 'Kingmaker: The Change of Destiny',
        'sous_titre' => 'Wind, Clouds and Rain',
        'poster' => 'images/image6.png',
        'resume' => [
            'Set at the end of the Joseon period, the series follows the face reader Choi Chun Joong as he tries to build an ideal nation. Regarded as the greatest fortune teller and physiognomist of Joseon, he is a hero of turbulent times with the great ambition of building a new country after overthrowing Joseon, ruined by those in power.',
            'Handsome and refined, Choi Chun Joong excels in the arts, including martial arts, gambling, singing and dancing. He is also a romantic who does everything for the woman he loves. With a way with words and a brilliant political mind, he will make Yi Ha Eung the most powerful man in Joseon, Yi Ha Eung’s son Lee Jae Hwang a king, and Min Ja Young, a girl from the streets, the empress of Joseon.',
            'Adapted from the novel “Baramgwa Gooreumgwa Bi” by Lee Byung Joo (serialized from 1977 to 1987 in The Chosun Ilbo), the story blends fictional characters with real historical figures.',
        ],
        'episodes_total' => '21',
        'durer' => '1 h',
        'diffuser_le' => 'From May 17, 2020',
        'reseau_origine' => 'TV Chosun',
        'pays' => 'South Korea',
        'statue' => 'Completed',
        'sortie' => '2020',
        'genre' => 'Drama ; Fantasy ; Historical ; Romance ; Supernatural',
        'casting' => [
            ['nom' => 'Jo Bok-rae', 'image' => 'images/image6.1.png'],
            ['nom' => 'Noh Hyeong-wook', 'image' => 'images/image6.2.png'],
            ['nom' => 'Park Jeong-yeon', 'image' => 'images/image6.3.png'],
            ['nom' => 'Kang Tae-woo', 'image' => 'images/image6.4.png'],
        ],
        'video_titre' => 'Kingmaker: The Change of Destiny trailer',
        'youtube_link' => 'https://www.youtube.com/watch?v=1uXLgYvG-OY',
        'video' => 'https://www.youtube-nocookie.com/embed/1uXLgYvG-OY',
    ],
    [
        'id' => 4,
        'titre' => 'Stealth Walker',
        'sous_titre' => 'Mei Gui Xing Zhe',
        'poster' => 'images/image3.0.png',
        'resume' => [
            'The story of a group of young police officers who take down drug trafficking organizations.',
        ],
        'episodes_total' => '10',
        'durer' => '50 min',
        'diffuser_le' => 'August 11 to 27, 2021',
        'reseau_origine' => 'Youku',
        'pays' => 'China',
        'statue' => 'Completed',
        'sortie' => '2021',
        'genre' => 'Crime ; Friendship ; Investigation ; Romance ; Suspense ; Web series',
        'casting' => [
            ['nom' => 'Peng Ling', 'image' => 'images/image3.1.png'],
            ['nom' => 'Zheng Ye Cheng', 'image' => 'images/image3.2.png'],
            ['nom' => 'Kim Ji-woong', 'image' => 'images/image33.png'],
            ['nom' => 'Li Zi Feng', 'image' => 'images/image3.4.png'],
        ],
        'video_titre' => 'Stealth Walker (2021) trailer',
        'youtube_link' => 'https://www.youtube.com/watch?v=GQhU9SVkQdk',
        'video' => 'https://www.youtube-nocookie.com/embed/GQhU9SVkQdk',
    ],
    [
        'id' => 5,
        'titre' => 'The Sweet Blood',
        'sous_titre' => 'Daldarhan Keu Nom',
        'poster' => 'images/image2.10.png',
        'resume' => [
            'Born to a human mother and a vampire father, Yeon Seo is a 118-year-old half-vampire who wants nothing more than an ordinary human life. She has chosen to blend in with people her apparent age and now faces one of life’s toughest challenges: graduating from high school.',
            'Fighting her vampire urges, Yeon Seo does her best to go unnoticed at school, until the sweet blood of her classmate Song Meo Roo attracts vampires and werewolves. Trying to ignore its call, she takes it upon herself to protect him from those who hunt him.',
            'Torn between family duty and the desires of her heart, will Yeon Seo embrace her humanity and resist temptation, or will her vampire side win in the end?',
        ],
        'episodes_total' => '15',
        'diffuser_le' => 'From April 7, 2021 (Wednesdays and Saturdays)',
        'reseau_origine' => 'YouTube (B-PLAY)',
        'pays' => 'South Korea',
        'statue' => 'Completed',
        'sortie' => '2021',
        'genre' => 'Fantasy ; Romance ; Vampires ; Web series',
        'casting' => [
            ['nom' => 'Kim Eo-jin', 'image' => 'images/image2.1.png'],
            ['nom' => 'Song Chae-yoon', 'image' => 'images/image2.2.png'],
            ['nom' => 'Jo Eun-ho', 'image' => 'images/image2.3-1998.png'],
            ['nom' => 'Kim Tae-hwan', 'image' => 'images/image2.4.png'],
        ],
        'video_titre' => 'The Sweet Blood (2021) trailer',
        'youtube_link' => 'https://www.youtube.com/watch?v=qB6lC96tXUc',
        'video' => 'https://www.youtube-nocookie.com/embed/qB6lC96tXUc',
    ],
];
