<?php

// Fiches mangas (version française).
// 'texte' est le résumé (liste de paragraphes), 'description' une courte présentation.

$categorie1 = [
    [
        'id' => 1,
        'titre' => 'Chainsaw Man T01',
        'sous_titre' => 'Denji et le démon tronçonneuse',
        'image' => 'images/mangas10.jpg',
        'texte' => [
            'Le jeune Denji a un rêve simple : vivre une vie heureuse et paisible, en passant du temps avec la fille qu’il aime. La réalité est bien différente : les yakuzas le contraignent à tuer des démons pour rembourser ses dettes écrasantes. Se servant de son démon Pochita comme d’une arme, il est prêt à tout pour un peu d’argent.',
            'Hélas, il ne fait plus l’affaire et est assassiné par un diable en contrat avec les yakuzas. Dans une tournure inattendue, Pochita fusionne avec le corps de Denji et lui confère les pouvoirs d’un démon tronçonneur. Capable de transformer des parties de son corps en tronçonneuses, Denji, une fois ressuscité, élimine ses ennemis rapidement et brutalement.',
            'Les chasseurs de démons officiels arrivés sur les lieux l’admirent et lui proposent de travailler au Bureau de la sécurité publique. Désormais armé pour affronter les ennemis les plus coriaces, Denji ne reculera devant rien pour réaliser ses rêves d’adolescent.',
        ],
        'description' => 'Premier tome d’une série d’action et d’horreur publiée dans le Weekly Shonen Jump, qui mêle combats brutaux et humour noir.',
        'genre' => 'Shonen - Action - Horreur - Fantastique',
        'date' => '2020',
        'nombre_de_tomes' => '11',
        'nombre_de_pages' => '192',
        'note' => '4,5/5',
        'prix' => '7,99 €',
        'auteurs' => ['Tatsuki Fujimoto'],
    ],
    [
        'id' => 2,
        'titre' => 'Stranger Case Vol. 1',
        'sous_titre' => 'In/Spectre',
        'image' => 'images/mangastome1.webp',
        'texte' => [
            'Dans son enfance, Kotoko a été enlevée et mutilée pour devenir la « déesse de la sagesse » des yôkai et autres créatures surnaturelles. Depuis, elle sert de lien entre leur monde et celui des humains.',
            'Tout se complique lorsqu’elle s’éprend de Kurô, un jeune homme au cœur brisé qui semble avoir un étrange effet sur ces êtres fabuleux : ils sont terrifiés à sa simple vue ! Quel est le secret du jeune homme ? Va-t-il pouvoir prêter main-forte à Kotoko dans son obscure mission ?',
        ],
        'description' => 'Un manga à mi-chemin entre enquête et fantastique, où la logique de Kotoko sert à résoudre des affaires mêlant humains et créatures surnaturelles.',
        'genre' => 'Action - Comédie - Drame - Surnaturel',
        'date' => '16/10/2015',
        'nombre_de_tomes' => '20',
        'nombre_de_pages' => '191',
        'note' => '8,64/10',
        'prix' => '7,20 €',
        'auteurs' => ['Kyo Shirodaira', 'Chashiba Katase'],
    ],
    [
        'id' => 3,
        'titre' => 'Solo Leveling Vol. 1',
        'sous_titre' => 'Le chasseur le plus faible du monde',
        'image' => 'images/mangas2tome2.webp',
        'texte' => [
            'Lorsque d’étranges portails sont apparus aux quatre coins du monde, l’humanité a dû trouver une parade pour ne pas être massacrée par les monstres qu’ils laissent passer. La solution ? Les chasseurs ! Ces combattants intrépides n’hésitent pas à foncer au cœur des donjons dimensionnels pour affronter les créatures qui s’y cachent et récolter des trésors.',
            'Jin Woo est le plus faible de tous les chasseurs : un jour, lors d’un raid, il succombe. Alors qu’il croyait sa vie finie, il se réveille à l’hôpital avec un étrange pouvoir : une interface virtuelle lui permet de passer des niveaux pour devenir plus fort ! L’occasion pour Jin Woo de prendre sa revanche et d’accéder au rang de chasseur le plus puissant ?',
        ],
        'description' => 'À l’origine un webtoon coréen (manhwa), Solo Leveling suit la progression fulgurante d’un chasseur considéré comme le plus faible de tous.',
        'genre' => 'Action - Fantasy',
        'date' => '07/04/2021',
        'nombre_de_tomes' => '14',
        'nombre_de_pages' => '190',
        'note' => '9,4/10',
        'prix' => '14,95 €',
        'auteurs' => ['Chugong', 'Jang Seong-rak'],
    ],
    [
        'id' => 4,
        'titre' => 'Mashle Vol. 1',
        'sous_titre' => 'Magic and Muscles',
        'image' => 'images/mangas4tome1.webp',
        'texte' => [
            'Dans un monde où la magie fait loi, il était une fois Mash Burnedead ! Élevé au fin fond de la forêt, le jeune garçon passe ses journées entre séances de musculation et dégustations de choux à la crème. Mais un jour, un policier découvre son secret : il est né sans pouvoirs magiques, ce qui est interdit par la loi !',
            'Pour survivre et vivre en paix avec son père, il devra postuler à Easton, une prestigieuse académie de magie, et devenir le meilleur élève. Avec ses muscles d’acier et sa force extraordinaire, Mash compte bien pulvériser tous les sorts et briser les codes de cette société.',
        ],
        'description' => 'Un premier tome hilarant et énergique : dans un monde où la magie est synonyme de survie, un héros sans pouvoir magique s’impose à coups de poing.',
        'genre' => 'Action - Aventure - Comédie - Fantastique',
        'date' => '04/06/2020',
        'nombre_de_tomes' => '18',
        'nombre_de_pages' => '189',
        'note' => '8,85/10',
        'prix' => '6,99 €',
        'auteurs' => ['Hajime Komoto'],
    ],
    [
        'id' => 5,
        'titre' => 'One-Punch Man Vol. 1',
        'sous_titre' => 'Saitama contre tous',
        'image' => 'images/mangas5tome1.webp',
        'texte' => [
            'Lorsque le super-héros Saitama se présente à ses ennemis, ces derniers ne le prennent jamais au sérieux. Il faut dire qu’entre sa carrure plutôt banale et son allure désinvolte, il n’y a pas vraiment de quoi avoir peur. Pourtant, Saitama possède une puissance colossale qui lui permet de terrasser ses adversaires en un seul coup !',
            'Cette puissance est due à trois ans d’entraînement très intensif, au point d’en perdre ses cheveux. Le problème, c’est que depuis, il s’ennuie : personne n’a encore pu rivaliser avec lui et il cherche désespérément celui qui pourra lui offrir un vrai combat.',
        ],
        'description' => 'Une parodie de super-héros drôle et spectaculaire, dans un monde plein de monstres où le héros s’ennuie car il gagne toujours.',
        'theme' => 'Aliens - Arts martiaux - Combats - Cyborgs - Monstres - Parodie - Super-héros - Super-pouvoirs',
        'genre' => 'Action - Comédie - Science-fiction - Surnaturel',
        'date' => '2012',
        'nombre_de_tomes' => '29',
        'nombre_de_pages' => '188',
        'note' => '8,90/10',
        'prix' => '6,95 €',
        'auteurs' => ['ONE', 'Yusuke Murata'],
    ],
];
